import { useEffect } from 'react';

export function AboutPage() {
  useEffect(() => {
    document.title = "About Undetecta";
  }, []);

  return (
    <main className="max-w-3xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <h1 className="text-2xl font-bold text-gray-900 mb-6">About Undetecta</h1>
      
      <div className="space-y-6 text-sm text-gray-600 leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">What is Undetecta?</h2>
          <p>
            Undetecta is a free, dual-purpose utility designed to help content creators, students, and professionals bridge the gap between artificial intelligence and natural human expression. It provides two core tools: an AI text humanizer to make robotic-sounding drafts feel more authentic, and an AI content detector to evaluate the probability that a piece of text was generated by AI.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">Who Built It?</h2>
          <p>
            Undetecta was created by Wasay, a solo indie developer passionate about building simple, effective, and accessible web tools. The goal was to create a lightweight, no-nonsense utility that anyone can use without having to jump through hoops or sign up for expensive subscriptions.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">How It Works</h2>
          <p>
            At a high level, the <strong>AI Humanizer</strong> analyzes the syntax, vocabulary, and predictable sentence structures common to large language models (like ChatGPT or Claude) and restructures them to mimic the varied, nuanced flow of a human writer. The <strong>AI Detector</strong> works in reverse, scanning text for those exact same predictable patterns to estimate the likelihood of machine generation.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">Data & Privacy</h2>
          <p>
            We respect your privacy. When you use Undetecta, your text is securely processed via third-party AI API calls in real-time to generate your results. <strong>Your submitted text is not permanently stored, saved, or logged on our servers.</strong> Once the processing is complete and the result is returned to your browser, the data is gone.
          </p>
        </section>
      </div>
    </main>
  );
}
