import { useEffect } from 'react';
import { DetectorTab } from '../components/DetectorTab';
import { Link } from 'react-router-dom';

export function DetectorPage() {
  useEffect(() => {
    document.title = "Free AI Detector - Check If Text Is AI-Generated | Undetecta";
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute('content', "Free AI content detector to check if text was written by ChatGPT, Claude, or Gemini. Get an instant AI-probability score. No signup required.");
    }
  }, []);

  return (
    <>
      <main className="max-w-7xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        
        {/* Intro Section */}
        <div className="max-w-3xl mx-auto text-center mb-10">
          <h1 className="text-2xl font-bold text-gray-900 mb-4">Free AI Detector – Check If Text Is AI-Generated</h1>
          <p className="text-gray-600 text-sm leading-relaxed">
            Our free AI detector analyzes your text to determine if it was generated by artificial intelligence. 
            Whether you are verifying the originality of content before publishing or checking a submission, 
            this tool helps you identify robotic patterns quickly and reliably.
          </p>
        </div>

        {/* The Detector Tool */}
        <div className="mb-16">
          <DetectorTab />
        </div>
        
      </main>

      {/* How It Works Section */}
      <section className="max-w-3xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <h2 className="text-xl font-semibold text-gray-900 mb-6">How it works</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100">
            <div className="w-8 h-8 bg-blue-50 text-blue-600 rounded-lg flex items-center justify-center font-bold mb-3">1</div>
            <h3 className="font-medium text-gray-900 mb-2">Paste Text</h3>
            <p className="text-sm text-gray-600">Copy the document you want to check and paste it into the input box.</p>
          </div>
          <div className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100">
            <div className="w-8 h-8 bg-blue-50 text-blue-600 rounded-lg flex items-center justify-center font-bold mb-3">2</div>
            <h3 className="font-medium text-gray-900 mb-2">Click Check</h3>
            <p className="text-sm text-gray-600">Press the Detect button to start the analysis of your text.</p>
          </div>
          <div className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100">
            <div className="w-8 h-8 bg-blue-50 text-blue-600 rounded-lg flex items-center justify-center font-bold mb-3">3</div>
            <h3 className="font-medium text-gray-900 mb-2">See AI Score</h3>
            <p className="text-sm text-gray-600">Instantly receive a percentage score indicating the probability of AI generation.</p>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="max-w-3xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <h2 className="text-xl font-semibold text-gray-900 mb-6">Frequently Asked Questions</h2>
        <div className="space-y-6">
          <div>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">What is an AI detector?</h3>
            <p className="text-sm text-gray-600">An AI detector is a tool that analyzes text to find predictable patterns, sentence structures, and vocabulary commonly used by AI language models.</p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">Is it free?</h3>
            <p className="text-sm text-gray-600">Yes, our AI detector is completely free to use with no account or signup required.</p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">Can it detect ChatGPT and Claude text?</h3>
            <p className="text-sm text-gray-600">Yes, it is designed to detect content generated by popular AI models like ChatGPT, Claude, Gemini, and others.</p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">How accurate is it?</h3>
            <p className="text-sm text-gray-600">While no detector is 100% perfect, our tool provides a highly reliable estimate based on advanced linguistic analysis, helping you make informed decisions.</p>
          </div>
        </div>
      </section>

      {/* Related Tools Section */}
      <section className="max-w-3xl mx-auto px-4 py-8 sm:px-6 lg:px-8 mb-8 text-center border-t border-gray-100 mt-8">
        <h2 className="text-lg font-medium text-gray-900 mb-4">Explore More Tools</h2>
        <Link 
          to="/ai-humanizer" 
          className="inline-flex items-center gap-2 px-6 py-3 bg-white border border-gray-200 text-gray-700 rounded-xl hover:bg-gray-50 hover:border-gray-300 transition-all font-medium text-sm shadow-sm"
        >
          Check out our Free AI Humanizer
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
        </Link>
      </section>
    </>
  );
}
