import { useEffect } from 'react';
import { HumanizerTab } from '../components/HumanizerTab';
import { Link } from 'react-router-dom';

export function HumanizerPage() {
  useEffect(() => {
    document.title = "Free AI Humanizer - Make AI Text Sound Natural | Undetecta";
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute('content', "Free AI humanizer tool to rewrite ChatGPT, Claude & Gemini text so it sounds natural and human. No signup required.");
    }
  }, []);

  return (
    <>
      <main className="max-w-7xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        
        {/* Intro Section */}
        <div className="max-w-3xl mx-auto text-center mb-10">
          <h1 className="text-2xl font-bold text-gray-900 mb-4">Free AI Humanizer – Make AI Text Sound Natural</h1>
          <p className="text-gray-600 text-sm leading-relaxed">
            Our AI humanizer is designed to transform robotic, predictable AI-generated text into natural, fluent human writing. 
            Whether you are trying to avoid false flags from AI detection tools, or you simply want your drafts to sound more personal and engaging, 
            this tool seamlessly rewrites your content to sound authentic.
          </p>
        </div>

        {/* The Humanizer Tool */}
        <div className="mb-16">
          <HumanizerTab />
        </div>
        
      </main>

      {/* How It Works Section */}
      <section className="max-w-3xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <h2 className="text-xl font-semibold text-gray-900 mb-6">How it works</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100">
            <div className="w-8 h-8 bg-blue-50 text-blue-600 rounded-lg flex items-center justify-center font-bold mb-3">1</div>
            <h3 className="font-medium text-gray-900 mb-2">Paste Text</h3>
            <p className="text-sm text-gray-600">Copy your ChatGPT, Claude, or Gemini draft and paste it into the input box.</p>
          </div>
          <div className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100">
            <div className="w-8 h-8 bg-blue-50 text-blue-600 rounded-lg flex items-center justify-center font-bold mb-3">2</div>
            <h3 className="font-medium text-gray-900 mb-2">Choose Tone</h3>
            <p className="text-sm text-gray-600">Select the tone (Standard, Casual, Professional, Academic) that best fits your needs.</p>
          </div>
          <div className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100">
            <div className="w-8 h-8 bg-blue-50 text-blue-600 rounded-lg flex items-center justify-center font-bold mb-3">3</div>
            <h3 className="font-medium text-gray-900 mb-2">Get Result</h3>
            <p className="text-sm text-gray-600">Click Humanize and instantly receive your natural-sounding, humanized rewrite.</p>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="max-w-3xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <h2 className="text-xl font-semibold text-gray-900 mb-6">Frequently Asked Questions</h2>
        <div className="space-y-6">
          <div>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">What is an AI humanizer?</h3>
            <p className="text-sm text-gray-600">An AI humanizer is a specialized tool that rewrites machine-generated text to remove robotic phrasing and predictable patterns, making it sound as if a real person wrote it.</p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">Is it free?</h3>
            <p className="text-sm text-gray-600">Yes, our AI humanizer is completely free to use with no account or signup required.</p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">Does it work with ChatGPT and Claude text?</h3>
            <p className="text-sm text-gray-600">Yes, it effectively humanizes content generated by ChatGPT, Claude, Google Gemini, and any other AI writing assistant.</p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">Will it change my meaning?</h3>
            <p className="text-sm text-gray-600">Our tool is designed to preserve your original intent and core message while only altering the sentence structure and vocabulary to sound more natural.</p>
          </div>
        </div>
      </section>

      {/* Related Tools Section */}
      <section className="max-w-3xl mx-auto px-4 py-8 sm:px-6 lg:px-8 mb-8 text-center border-t border-gray-100 mt-8">
        <h2 className="text-lg font-medium text-gray-900 mb-4">Explore More Tools</h2>
        <Link 
          to="/ai-detector" 
          className="inline-flex items-center gap-2 px-6 py-3 bg-white border border-gray-200 text-gray-700 rounded-xl hover:bg-gray-50 hover:border-gray-300 transition-all font-medium text-sm shadow-sm"
        >
          Check out our Free AI Detector
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
        </Link>
      </section>
    </>
  );
}
