import { useEffect } from 'react';

export function TermsPage() {
  useEffect(() => {
    document.title = "Terms of Service - Undetecta";
  }, []);

  return (
    <main className="max-w-3xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <h1 className="text-2xl font-bold text-gray-900 mb-6">Terms of Service</h1>
      
      <div className="space-y-6 text-sm text-gray-600 leading-relaxed">
        <p>Last updated: September 2, 2026</p>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing and using Undetecta, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">2. Acceptable Use</h2>
          <p>
            Undetecta is provided as a free utility for personal and professional use. You agree not to use the service for any unlawful purpose, or in any way that could damage, disable, overburden, or impair our servers or networks. We reserve the right to limit or block access to users who abuse the service with excessive automated requests.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">3. Intellectual Property</h2>
          <p>
            You retain all rights and ownership to the text you submit to Undetecta. We claim no ownership over the original input or the resulting output generated by our tools. 
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">4. Disclaimer of Warranties</h2>
          <p>
            The service is provided on an "as-is" and "as available" basis. Undetecta makes no warranties, expressed or implied, and hereby disclaims all warranties, including without limitation, implied warranties of merchantability, fitness for a particular purpose, or non-infringement of intellectual property. We do not guarantee that the AI detector is 100% accurate, nor do we guarantee that the AI humanizer will perfectly bypass all detection systems.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">5. Limitation of Liability</h2>
          <p>
            In no event shall Undetecta, its creator (Wasay), or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Undetecta's website.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">6. Modifications to Service</h2>
          <p>
            We reserve the right to modify, suspend, or discontinue, temporarily or permanently, the service (or any part thereof) with or without notice. You agree that we shall not be liable to you or to any third party for any modification, suspension, or discontinuance of the service.
          </p>
        </section>
      </div>
    </main>
  );
}
