import { useState } from 'react';
import { Header } from './components/Header';
import { HumanizerTab } from './components/HumanizerTab';
import { DetectorTab } from './components/DetectorTab';

type Tab = 'humanize' | 'detect';

export default function App() {
  const [activeTab, setActiveTab] = useState<Tab>('humanize');

  return (
    <div className="min-h-screen bg-gray-50 text-gray-900 font-sans selection:bg-blue-100">
      <Header />
      
      <main className="max-w-7xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        
        {/* Tab Switcher */}
        <div className="flex justify-center mb-8">
          <div className="bg-white p-1 rounded-2xl shadow-sm border border-gray-100 inline-flex" role="tablist" aria-label="Tool sections">
            <button
              role="tab"
              aria-selected={activeTab === 'humanize'}
              aria-controls="humanize-panel"
              onClick={() => setActiveTab('humanize')}
              className={`px-6 py-2.5 rounded-xl font-medium text-sm transition-all ${
                activeTab === 'humanize' 
                  ? 'bg-blue-50 text-blue-700 shadow-sm' 
                  : 'text-gray-500 hover:text-gray-900 hover:bg-gray-50'
              }`}
            >
              Humanize Text
            </button>
            <button
              role="tab"
              aria-selected={activeTab === 'detect'}
              aria-controls="detect-panel"
              onClick={() => setActiveTab('detect')}
              className={`px-6 py-2.5 rounded-xl font-medium text-sm transition-all ${
                activeTab === 'detect' 
                  ? 'bg-blue-50 text-blue-700 shadow-sm' 
                  : 'text-gray-500 hover:text-gray-900 hover:bg-gray-50'
              }`}
            >
              Detect AI Text
            </button>
          </div>
        </div>

        {/* Active Tab Content */}
        <div 
          id={activeTab === 'humanize' ? "humanize-panel" : "detect-panel"} 
          role="tabpanel"
        >
          {activeTab === 'humanize' ? <HumanizerTab /> : <DetectorTab />}
        </div>
        
      </main>

      {/* About Section */}
      <section className="max-w-3xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">About Undetecta</h2>
        <div className="space-y-4 text-sm text-gray-600 leading-relaxed">
          <p>
            Undetecta is a dual-purpose tool designed to bridge the gap between artificial intelligence and natural human expression. It functions as both a sophisticated AI text humanizer and an accurate AI content detector, giving you complete control over how your writing is perceived.
          </p>
          <p>
            Whether you are a student, content writer, marketer, or professional, Undetecta helps ensure your AI-assisted drafts sound authentic and resonate with human readers. It refines rigid, robotic structures into fluid, natural phrasing that feels personal and engaging.
          </p>
          <p>
            To get started, simply paste your text into the humanizer, select your desired tone, and instantly receive a human-sounding rewrite. Alternatively, switch to the free AI detector tab to scan any piece of writing and evaluate its likelihood of being flagged as AI-generated by common detection tools.
          </p>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="max-w-3xl mx-auto px-4 pb-12 sm:px-6 lg:px-8">
        <h2 className="text-xl font-semibold text-gray-900 mb-6">Frequently Asked Questions</h2>
        <div className="space-y-6">
          <div>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">Does Undetecta work with ChatGPT, Claude, and Gemini text?</h3>
            <p className="text-sm text-gray-600">Yes, it works seamlessly with text generated by any AI writing tool.</p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">Can Undetecta bypass Turnitin and GPTZero?</h3>
            <p className="text-sm text-gray-600">Undetecta rewrites text to sound more natural and fluid, which helps significantly reduce AI-detection flags from common analysis tools.</p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">Is Undetecta free to use?</h3>
            <p className="text-sm text-gray-600">Yes, Undetecta is completely free to use with no signup or account required.</p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">How does the AI detector work?</h3>
            <p className="text-sm text-gray-600">It analyzes textual patterns, sentence structure predictability, and vocabulary to estimate the probability that the content was AI-generated.</p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">Is it safe to use Undetecta for student assignments?</h3>
            <p className="text-sm text-gray-600">We strongly recommend that students always consult and follow their school's specific academic integrity policies regarding the use of AI assistance.</p>
          </div>
        </div>
      </section>

      {/* Credit Footer */}
      <footer className="text-center pb-6 pt-2 text-xs text-gray-400">
        Built by Wasay
      </footer>
    </div>
  );
}
